set number                                                                                                                                                                                                                                                     
set hidden                                                                                                                                                                                                                                                     
set nocp                                                                                                                                                                                                                                                       
set grepprg=rg\ --vimgrep\ --smart-case\ --follow                                                                                                                                                                                                              
set backspace=indent,eol,start                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
set tabstop=4                                                                                                                                                                                                                                                  
set shiftwidth=4                                                                                                                                                                                                                                               
set expandtab                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
filetype plugin on                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
" Automatic installation for plug.vim                                                                                                                                                                                                                          
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'                                                                                                                                                                                              
if empty(glob(data_dir . '/autoload/plug.vim'))                                                                                                                                                                                                                
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'                                                                                                                
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC                                                                                                                                                                                                      
endif                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
call plug#begin()                                                                                                                                                                                                                                              
Plug 'junegunn/fzf.vim'                                                                                                                                                                                                                                        
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }                                                                                                                                                                                                            
Plug 'morhetz/gruvbox'                                                                                                                                                                                                                                         
Plug 'gustafj/vim-ttcn'                                                                                                                                                                                                                                        
call plug#end()                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
set background=dark                                                                                                                                                                                                                                            
colorscheme gruvbox